//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkwadArabia.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestPage_DDL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void RequestPage_DDL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestPage_DDL", ReplyAction="*")]
        System.Threading.Tasks.Task RequestPage_DDLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Request_SEL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Request_SEL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Request_SEL", ReplyAction="*")]
        System.Threading.Tasks.Task Request_SELAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/REQUEST_INS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void REQUEST_INS(string REQUEST_TYPE_ID, string REQ_DATE, string BUILDING_ID, string DEPARTMENT_ID, string EMPLOYEE_NAME, string EMPLOYEE_MOBILE, string EMPLOYEE_PHONE, string CATEGORY_MASTER_ID, string CATEGORY_DETAIL_ID, string PLACE, string DESCREPTION, string NOTES, string DAY_NIGHT_D_N);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/REQUEST_INS", ReplyAction="*")]
        System.Threading.Tasks.Task REQUEST_INSAsync(string REQUEST_TYPE_ID, string REQ_DATE, string BUILDING_ID, string DEPARTMENT_ID, string EMPLOYEE_NAME, string EMPLOYEE_MOBILE, string EMPLOYEE_PHONE, string CATEGORY_MASTER_ID, string CATEGORY_DETAIL_ID, string PLACE, string DESCREPTION, string NOTES, string DAY_NIGHT_D_N);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : AkwadArabia.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<AkwadArabia.ServiceReference1.WebServiceSoap>, AkwadArabia.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RequestPage_DDL() {
            base.Channel.RequestPage_DDL();
        }
        
        public System.Threading.Tasks.Task RequestPage_DDLAsync() {
            return base.Channel.RequestPage_DDLAsync();
        }
        
        public void Request_SEL() {
            base.Channel.Request_SEL();
        }
        
        public System.Threading.Tasks.Task Request_SELAsync() {
            return base.Channel.Request_SELAsync();
        }
        
        public void REQUEST_INS(string REQUEST_TYPE_ID, string REQ_DATE, string BUILDING_ID, string DEPARTMENT_ID, string EMPLOYEE_NAME, string EMPLOYEE_MOBILE, string EMPLOYEE_PHONE, string CATEGORY_MASTER_ID, string CATEGORY_DETAIL_ID, string PLACE, string DESCREPTION, string NOTES, string DAY_NIGHT_D_N) {
            base.Channel.REQUEST_INS(REQUEST_TYPE_ID, REQ_DATE, BUILDING_ID, DEPARTMENT_ID, EMPLOYEE_NAME, EMPLOYEE_MOBILE, EMPLOYEE_PHONE, CATEGORY_MASTER_ID, CATEGORY_DETAIL_ID, PLACE, DESCREPTION, NOTES, DAY_NIGHT_D_N);
        }
        
        public System.Threading.Tasks.Task REQUEST_INSAsync(string REQUEST_TYPE_ID, string REQ_DATE, string BUILDING_ID, string DEPARTMENT_ID, string EMPLOYEE_NAME, string EMPLOYEE_MOBILE, string EMPLOYEE_PHONE, string CATEGORY_MASTER_ID, string CATEGORY_DETAIL_ID, string PLACE, string DESCREPTION, string NOTES, string DAY_NIGHT_D_N) {
            return base.Channel.REQUEST_INSAsync(REQUEST_TYPE_ID, REQ_DATE, BUILDING_ID, DEPARTMENT_ID, EMPLOYEE_NAME, EMPLOYEE_MOBILE, EMPLOYEE_PHONE, CATEGORY_MASTER_ID, CATEGORY_DETAIL_ID, PLACE, DESCREPTION, NOTES, DAY_NIGHT_D_N);
        }
    }
}
